name: quote_generator

on:
  workflow_dispatch:
  # 00:00 UTC
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - name: Generate quote
      run: npm run generate
    - name: Update README.md
      run: |
        git config --global user.email "kietnguyen17052001@gmail.com"
        git config --global user.name "ngdangkiet"
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        git add .
        git commit -m "Updated README.md at $timestamp" || echo "No changes to commit"
        git push
