name: quote_generator

on:
  workflow_dispatch:
  # Run every hour
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup environment
        env:
          PORT: ${{ secrets.PORT }}
          URL: ${{ secrets.URL }}
        run: |
          echo "PORT=$PORT" >> .env
          echo "URL=$URL" >> .env

      - run: npm ci

      - name: Generate quote
        run: npm run generate

      - name: Update README.md
        run: |
          git config --global user.email "kietnguyen17052001@gmail.com"
          git config --global user.name "ngdangkiet"
          timestamp=$(TZ=Asia/Ho_Chi_Minh date +"%Y-%m-%d %H:%M:%S %Z")
          git add .
          git commit -m "Updated README.md at $timestamp" || echo "No changes to commit"
          git push
