name: quote_generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP_COMMIT: $(TZ=Asia/Ho_Chi_Minh date +"%Y-%m-%d %H:%M:%S %Z")
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: git pull origin master

      # NodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup environment
        env:
          PORT: ${{ secrets.PORT }}
          URL: ${{ secrets.URL }}
        run: |
          echo "PORT=$PORT" >> .env
          echo "URL=$URL" >> .env

      - run: npm ci

      - name: Generate quote
        run: npm run generate

      - name: Update README.md
        run: |
          git config --global user.email "kietnguyen17052001@gmail.com"
          git config --global user.name "ngdangkiet"
          git add .
          git commit -m "Updated README.md at ${{ env.TIMESTAMP_COMMIT }}" || echo "No changes to commit"
          git push

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Git Commit Data
        uses: rlespinasse/git-commit-data-action@v1.5.0

      # Docker
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and push Docker image
        run: |
          # Extract the branch name and commit hash
          TIMESTAMP=$(TZ=Asia/Ho_Chi_Minh date +"%Y%m%d%H%M%S")
          BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}
          COMMIT_SHA=${{ env.GIT_COMMIT_SHORT_SHA }}
          IMAGE_NAME="01092002/ngdangkiet-nodejs"
          IMAGE_TAG="$BRANCH_NAME-$COMMIT_SHA-$TIMESTAMP"

          # Build the Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

          # Push the images to Docker Hub
          docker push $IMAGE_NAME:$IMAGE_TAG

      # Telegram
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New commit 👇
            https://github.com/${{ github.repository }}/commit/${{github.sha}}
